import type { ActivityEntry, AccentTone, FileEntry, FileStatus, SectionId } from '@/types/file-manager';

export const accentThemeMap: Record<
	AccentTone,
	{
		chip: string;
		bar: string;
		surface: string;
		ring: string;
		glow: string;
	}
> = {
	sky: {
		chip: 'bg-sky-500/12 text-sky-700 dark:bg-sky-400/12 dark:text-sky-200',
		bar: 'bg-sky-500',
		surface: 'from-sky-500/12 via-sky-500/3 to-transparent',
		ring: 'ring-sky-300/50',
		glow: 'shadow-[0_18px_34px_rgba(14,165,233,0.18)]',
	},
	emerald: {
		chip: 'bg-emerald-500/12 text-emerald-700 dark:bg-emerald-400/12 dark:text-emerald-200',
		bar: 'bg-emerald-500',
		surface: 'from-emerald-500/12 via-emerald-500/3 to-transparent',
		ring: 'ring-emerald-300/50',
		glow: 'shadow-[0_18px_34px_rgba(16,185,129,0.18)]',
	},
	amber: {
		chip: 'bg-amber-500/12 text-amber-700 dark:bg-amber-400/12 dark:text-amber-200',
		bar: 'bg-amber-500',
		surface: 'from-amber-500/12 via-amber-500/3 to-transparent',
		ring: 'ring-amber-300/50',
		glow: 'shadow-[0_18px_34px_rgba(245,158,11,0.18)]',
	},
	violet: {
		chip: 'bg-violet-500/12 text-violet-700 dark:bg-violet-400/12 dark:text-violet-200',
		bar: 'bg-violet-500',
		surface: 'from-violet-500/12 via-violet-500/3 to-transparent',
		ring: 'ring-violet-300/50',
		glow: 'shadow-[0_18px_34px_rgba(139,92,246,0.18)]',
	},
	rose: {
		chip: 'bg-rose-500/12 text-rose-700 dark:bg-rose-400/12 dark:text-rose-200',
		bar: 'bg-rose-500',
		surface: 'from-rose-500/12 via-rose-500/3 to-transparent',
		ring: 'ring-rose-300/50',
		glow: 'shadow-[0_18px_34px_rgba(244,63,94,0.18)]',
	},
	cyan: {
		chip: 'bg-cyan-500/12 text-cyan-700 dark:bg-cyan-400/12 dark:text-cyan-200',
		bar: 'bg-cyan-500',
		surface: 'from-cyan-500/12 via-cyan-500/3 to-transparent',
		ring: 'ring-cyan-300/50',
		glow: 'shadow-[0_18px_34px_rgba(6,182,212,0.18)]',
	},
	slate: {
		chip: 'bg-slate-500/12 text-slate-700 dark:bg-slate-400/12 dark:text-slate-200',
		bar: 'bg-slate-500',
		surface: 'from-slate-500/12 via-slate-500/3 to-transparent',
		ring: 'ring-slate-300/50',
		glow: 'shadow-[0_18px_34px_rgba(100,116,139,0.18)]',
	},
};

export const statusToneMap: Record<FileStatus, string> = {
	synced: 'bg-emerald-500/12 text-emerald-700 dark:bg-emerald-400/12 dark:text-emerald-200',
	shared: 'bg-cyan-500/12 text-cyan-700 dark:bg-cyan-400/12 dark:text-cyan-200',
	draft: 'bg-amber-500/12 text-amber-700 dark:bg-amber-400/12 dark:text-amber-200',
	favorite: 'bg-rose-500/12 text-rose-700 dark:bg-rose-400/12 dark:text-rose-200',
	local: 'bg-slate-500/12 text-slate-700 dark:bg-slate-400/12 dark:text-slate-200',
	recent: 'bg-violet-500/12 text-violet-700 dark:bg-violet-400/12 dark:text-violet-200',
};

export const categorySymbolMap: Record<FileEntry['category'], string> = {
	folder: 'F',
	document: 'D',
	spreadsheet: 'X',
	image: 'P',
	video: 'V',
	archive: 'Z',
	code: '</>',
	pdf: 'PDF',
	audio: 'A',
};

export const seededEntries: Record<SectionId, FileEntry[]> = {
	home: [
		{
			id: 'home-design-sprint',
			name: 'Design Sprint',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Project folder',
			sizeLabel: '18 items',
			sortSize: 18,
			modifiedAt: '2026-05-02T07:30:00.000Z',
			preview: 'Wireframes, product copy, and final export batches for the next planning review.',
			status: 'favorite',
			accent: 'emerald',
			locationPath: ['LFM', 'Home', 'Design Sprint'],
			tags: ['UI', 'handoff', 'priority'],
			collaborators: ['Mia', 'Omar', 'Lina'],
			pinned: true
		},
		{
			id: 'home-quarterly-brief',
			name: 'Quarterly Brief.pdf',
			kind: 'file',
			category: 'pdf',
			typeLabel: 'PDF document',
			sizeLabel: '4.8 MB',
			sortSize: 4800,
			modifiedAt: '2026-05-02T06:12:00.000Z',
			preview: 'Board-ready summary of roadmap progress, blockers, and proposed staffing shifts.',
			status: 'shared',
			accent: 'sky',
			locationPath: ['LFM', 'Home', 'Quarterly Brief.pdf'],
			tags: ['briefing', 'finance'],
			collaborators: ['Rita', 'Sam'],
			pinned: false
		},
		{
			id: 'home-capture-kit',
			name: 'Capture Kit',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Media collection',
			sizeLabel: '42 items',
			sortSize: 42,
			modifiedAt: '2026-05-01T21:04:00.000Z',
			preview: 'Launch screenshots, icon exports, and compressed poster variants prepared for marketing.',
			status: 'recent',
			accent: 'rose',
			locationPath: ['LFM', 'Home', 'Capture Kit'],
			tags: ['marketing', 'assets'],
			collaborators: ['Noah', 'Dina'],
			pinned: true
		},
		{
			id: 'home-release-plan',
			name: 'Release Plan.md',
			kind: 'file',
			category: 'code',
			typeLabel: 'Markdown plan',
			sizeLabel: '38 KB',
			sortSize: 38,
			modifiedAt: '2026-05-01T17:26:00.000Z',
			preview: 'Milestones for packaging, QA, telemetry review, and staged rollout across stable channels.',
			status: 'draft',
			accent: 'amber',
			locationPath: ['LFM', 'Home', 'Release Plan.md'],
			tags: ['release', 'ops'],
			collaborators: ['Alya'],
			pinned: false
		},
		{
			id: 'home-invoices',
			name: 'Invoices',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Secure folder',
			sizeLabel: '9 items',
			sortSize: 9,
			modifiedAt: '2026-04-29T12:18:00.000Z',
			preview: 'Signed invoices, procurement receipts, and bookkeeping exports for the current cycle.',
			status: 'local',
			accent: 'violet',
			locationPath: ['LFM', 'Home', 'Invoices'],
			tags: ['private', 'accounting'],
			collaborators: ['You'],
			pinned: false
		}
	],
	documents: [
		{
			id: 'doc-operations-handbook',
			name: 'Operations Handbook.docx',
			kind: 'file',
			category: 'document',
			typeLabel: 'Word document',
			sizeLabel: '1.2 MB',
			sortSize: 1200,
			modifiedAt: '2026-05-01T14:00:00.000Z',
			preview: 'Standard operating procedures for support, incident response, and release communication.',
			status: 'shared',
			accent: 'violet',
			locationPath: ['LFM', 'Documents', 'Operations Handbook.docx'],
			tags: ['ops', 'support'],
			collaborators: ['Mira', 'Youssef'],
			pinned: false
		},
		{
			id: 'doc-budget-forecast',
			name: 'Budget Forecast.xlsx',
			kind: 'file',
			category: 'spreadsheet',
			typeLabel: 'Spreadsheet',
			sizeLabel: '872 KB',
			sortSize: 872,
			modifiedAt: '2026-04-30T08:45:00.000Z',
			preview: 'Expense model covering infrastructure, hiring, and launch campaign scenarios.',
			status: 'favorite',
			accent: 'emerald',
			locationPath: ['LFM', 'Documents', 'Budget Forecast.xlsx'],
			tags: ['finance', 'forecast'],
			collaborators: ['Hassan'],
			pinned: true
		},
		{
			id: 'doc-contracts',
			name: 'Contracts',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Legal folder',
			sizeLabel: '13 items',
			sortSize: 13,
			modifiedAt: '2026-04-26T10:20:00.000Z',
			preview: 'Vendor agreements, redlined renewals, and signature-ready PDFs.',
			status: 'local',
			accent: 'slate',
			locationPath: ['LFM', 'Documents', 'Contracts'],
			tags: ['legal'],
			collaborators: ['You', 'Legal'],
			pinned: false
		},
		{
			id: 'doc-release-checklist',
			name: 'Release Checklist.md',
			kind: 'file',
			category: 'code',
			typeLabel: 'Markdown checklist',
			sizeLabel: '21 KB',
			sortSize: 21,
			modifiedAt: '2026-05-02T05:05:00.000Z',
			preview: 'Preflight checks for build verification, smoke tests, package signing, and rollback readiness.',
			status: 'recent',
			accent: 'amber',
			locationPath: ['LFM', 'Documents', 'Release Checklist.md'],
			tags: ['qa', 'release'],
			collaborators: ['QA'],
			pinned: false
		},
		{
			id: 'doc-team-charter',
			name: 'Team Charter.pdf',
			kind: 'file',
			category: 'pdf',
			typeLabel: 'PDF charter',
			sizeLabel: '614 KB',
			sortSize: 614,
			modifiedAt: '2026-04-22T15:40:00.000Z',
			preview: 'Operating principles, ownership boundaries, and cross-functional escalation paths.',
			status: 'synced',
			accent: 'sky',
			locationPath: ['LFM', 'Documents', 'Team Charter.pdf'],
			tags: ['team'],
			collaborators: ['Leadership'],
			pinned: false
		}
	],
	downloads: [
		{
			id: 'dl-tauri-nightly',
			name: 'tauri-nightly.AppImage',
			kind: 'file',
			category: 'archive',
			typeLabel: 'Executable package',
			sizeLabel: '88 MB',
			sortSize: 88000,
			modifiedAt: '2026-05-02T04:12:00.000Z',
			preview: 'Nightly desktop build for testing native shell behaviors before the next milestone freeze.',
			status: 'recent',
			accent: 'amber',
			locationPath: ['LFM', 'Downloads', 'tauri-nightly.AppImage'],
			tags: ['build', 'nightly'],
			collaborators: ['You'],
			pinned: false
		},
		{
			id: 'dl-font-pack',
			name: 'Font Pack.zip',
			kind: 'file',
			category: 'archive',
			typeLabel: 'Compressed archive',
			sizeLabel: '274 MB',
			sortSize: 274000,
			modifiedAt: '2026-05-01T18:44:00.000Z',
			preview: 'Typeface bundle for upcoming campaign layouts and in-app branded collateral.',
			status: 'local',
			accent: 'rose',
			locationPath: ['LFM', 'Downloads', 'Font Pack.zip'],
			tags: ['assets'],
			collaborators: ['Creative'],
			pinned: false
		},
		{
			id: 'dl-qa-captures',
			name: 'QA Captures',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Import folder',
			sizeLabel: '32 items',
			sortSize: 32,
			modifiedAt: '2026-05-01T15:10:00.000Z',
			preview: 'Screenshots and clips gathered during the latest regression run.',
			status: 'shared',
			accent: 'sky',
			locationPath: ['LFM', 'Downloads', 'QA Captures'],
			tags: ['qa', 'screenshots'],
			collaborators: ['QA', 'Design'],
			pinned: false
		},
		{
			id: 'dl-client-video',
			name: 'Client Feedback.mp4',
			kind: 'file',
			category: 'video',
			typeLabel: 'Video clip',
			sizeLabel: '186 MB',
			sortSize: 186000,
			modifiedAt: '2026-04-30T11:15:00.000Z',
			preview: 'Walkthrough recording with annotations around navigation density and preview ergonomics.',
			status: 'shared',
			accent: 'cyan',
			locationPath: ['LFM', 'Downloads', 'Client Feedback.mp4'],
			tags: ['feedback', 'video'],
			collaborators: ['Client'],
			pinned: false
		},
		{
			id: 'dl-kernel-notes',
			name: 'linux-kernel-notes.txt',
			kind: 'file',
			category: 'document',
			typeLabel: 'Text note',
			sizeLabel: '12 KB',
			sortSize: 12,
			modifiedAt: '2026-04-28T09:10:00.000Z',
			preview: 'Collected notes on mount permissions, filesystem notifications, and watcher edge cases.',
			status: 'synced',
			accent: 'slate',
			locationPath: ['LFM', 'Downloads', 'linux-kernel-notes.txt'],
			tags: ['linux', 'notes'],
			collaborators: ['You'],
			pinned: false
		}
	],
	projects: [
		{
			id: 'proj-lfm-shell',
			name: 'LFM Shell',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Workspace',
			sizeLabel: '57 items',
			sortSize: 57,
			modifiedAt: '2026-05-02T07:56:00.000Z',
			preview: 'Vue shell, router structure, command bar ideas, and preview-pane experiments.',
			status: 'favorite',
			accent: 'emerald',
			locationPath: ['LFM', 'Projects', 'LFM Shell'],
			tags: ['vue', 'tauri'],
			collaborators: ['You', 'Frontend'],
			pinned: true
		},
		{
			id: 'proj-rust-commands',
			name: 'Rust Commands',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Backend module',
			sizeLabel: '23 items',
			sortSize: 23,
			modifiedAt: '2026-05-01T23:00:00.000Z',
			preview: 'Native filesystem actions, trash handling, metadata hydration, and command bindings.',
			status: 'synced',
			accent: 'sky',
			locationPath: ['LFM', 'Projects', 'Rust Commands'],
			tags: ['rust', 'backend'],
			collaborators: ['Backend'],
			pinned: false
		},
		{
			id: 'proj-ui-references',
			name: 'UI References.fig',
			kind: 'file',
			category: 'image',
			typeLabel: 'Design board',
			sizeLabel: '18 MB',
			sortSize: 18000,
			modifiedAt: '2026-05-01T19:34:00.000Z',
			preview: 'Reference board for surfaces, nav density, motion cues, and Explorer-inspired spacing.',
			status: 'shared',
			accent: 'rose',
			locationPath: ['LFM', 'Projects', 'UI References.fig'],
			tags: ['design', 'reference'],
			collaborators: ['Design Team'],
			pinned: false
		},
		{
			id: 'proj-sync-prototype',
			name: 'Sync Prototype',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Experiment folder',
			sizeLabel: '11 items',
			sortSize: 11,
			modifiedAt: '2026-04-30T16:22:00.000Z',
			preview: 'Offline queue drafts, sync markers, and conflict-state explorations for future milestones.',
			status: 'draft',
			accent: 'amber',
			locationPath: ['LFM', 'Projects', 'Sync Prototype'],
			tags: ['sync', 'prototype'],
			collaborators: ['Platform'],
			pinned: false
		},
		{
			id: 'proj-benchmarks',
			name: 'Benchmarks.csv',
			kind: 'file',
			category: 'spreadsheet',
			typeLabel: 'Metrics sheet',
			sizeLabel: '148 KB',
			sortSize: 148,
			modifiedAt: '2026-04-29T08:10:00.000Z',
			preview: 'Directory read timings, image decode stats, and large-folder rendering deltas.',
			status: 'recent',
			accent: 'violet',
			locationPath: ['LFM', 'Projects', 'Benchmarks.csv'],
			tags: ['performance'],
			collaborators: ['QA', 'Perf'],
			pinned: false
		}
	],
	media: [
		{
			id: 'media-hero-shots',
			name: 'Hero Shots',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Photo set',
			sizeLabel: '96 items',
			sortSize: 96,
			modifiedAt: '2026-05-02T03:16:00.000Z',
			preview: 'Desktop screenshots and showcase stills for the release page and in-app onboarding.',
			status: 'favorite',
			accent: 'rose',
			locationPath: ['LFM', 'Media', 'Hero Shots'],
			tags: ['photos', 'marketing'],
			collaborators: ['Creative'],
			pinned: true
		},
		{
			id: 'media-launch-trailer',
			name: 'Launch Trailer.mp4',
			kind: 'file',
			category: 'video',
			typeLabel: 'Video master',
			sizeLabel: '412 MB',
			sortSize: 412000,
			modifiedAt: '2026-05-01T12:52:00.000Z',
			preview: 'Final launch trailer with updated logo sequence and new keyboard-navigation scenes.',
			status: 'shared',
			accent: 'cyan',
			locationPath: ['LFM', 'Media', 'Launch Trailer.mp4'],
			tags: ['video', 'launch'],
			collaborators: ['Creative', 'Marketing'],
			pinned: false
		},
		{
			id: 'media-icon-drafts',
			name: 'Icon Drafts',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Asset folder',
			sizeLabel: '27 items',
			sortSize: 27,
			modifiedAt: '2026-04-30T09:50:00.000Z',
			preview: 'SVG iterations for file types, sidebar destinations, and command-bar states.',
			status: 'synced',
			accent: 'sky',
			locationPath: ['LFM', 'Media', 'Icon Drafts'],
			tags: ['icons', 'svg'],
			collaborators: ['Design'],
			pinned: false
		},
		{
			id: 'media-soundtrack',
			name: 'Soundtrack Mix.wav',
			kind: 'file',
			category: 'audio',
			typeLabel: 'Audio track',
			sizeLabel: '61 MB',
			sortSize: 61000,
			modifiedAt: '2026-04-28T18:40:00.000Z',
			preview: 'Ambient soundtrack mix used in concept videos and demo reels.',
			status: 'local',
			accent: 'violet',
			locationPath: ['LFM', 'Media', 'Soundtrack Mix.wav'],
			tags: ['audio'],
			collaborators: ['Sound'],
			pinned: false
		},
		{
			id: 'media-workshop-photos',
			name: 'Workshop Photos',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Image library',
			sizeLabel: '124 items',
			sortSize: 124,
			modifiedAt: '2026-04-26T13:08:00.000Z',
			preview: 'Behind-the-scenes photography from testing sessions and co-design workshops.',
			status: 'recent',
			accent: 'amber',
			locationPath: ['LFM', 'Media', 'Workshop Photos'],
			tags: ['photos', 'team'],
			collaborators: ['People Ops'],
			pinned: false
		}
	],
	shared: [
		{
			id: 'shared-design-review',
			name: 'Design Review',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Review folder',
			sizeLabel: '16 items',
			sortSize: 16,
			modifiedAt: '2026-05-02T02:10:00.000Z',
			preview: 'Annotated prototypes, stakeholder clips, and consolidated design comments.',
			status: 'shared',
			accent: 'cyan',
			locationPath: ['LFM', 'Shared', 'Design Review'],
			tags: ['review'],
			collaborators: ['Design', 'Product', 'Exec'],
			pinned: true
		},
		{
			id: 'shared-customer-mockups',
			name: 'Customer Mockups',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Presentation folder',
			sizeLabel: '24 items',
			sortSize: 24,
			modifiedAt: '2026-05-01T11:46:00.000Z',
			preview: 'Curated mockups tailored for enterprise demos and partner walkthroughs.',
			status: 'favorite',
			accent: 'rose',
			locationPath: ['LFM', 'Shared', 'Customer Mockups'],
			tags: ['demo', 'sales'],
			collaborators: ['Sales', 'Product'],
			pinned: true
		},
		{
			id: 'shared-release-assets',
			name: 'Release Assets',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Shared asset pack',
			sizeLabel: '31 items',
			sortSize: 31,
			modifiedAt: '2026-04-30T21:05:00.000Z',
			preview: 'Press images, changelog snippets, icon sheets, and store descriptions.',
			status: 'synced',
			accent: 'emerald',
			locationPath: ['LFM', 'Shared', 'Release Assets'],
			tags: ['release', 'marketing'],
			collaborators: ['Marketing'],
			pinned: false
		},
		{
			id: 'shared-stakeholder-notes',
			name: 'Stakeholder Notes.docx',
			kind: 'file',
			category: 'document',
			typeLabel: 'Collaborative note',
			sizeLabel: '342 KB',
			sortSize: 342,
			modifiedAt: '2026-04-28T15:55:00.000Z',
			preview: 'Consolidated feedback from the last steering committee checkpoint.',
			status: 'shared',
			accent: 'sky',
			locationPath: ['LFM', 'Shared', 'Stakeholder Notes.docx'],
			tags: ['notes'],
			collaborators: ['Leadership', 'Product'],
			pinned: false
		},
		{
			id: 'shared-feedback-clips',
			name: 'Feedback Clips',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Video review folder',
			sizeLabel: '7 items',
			sortSize: 7,
			modifiedAt: '2026-04-27T10:20:00.000Z',
			preview: 'Short recorded reactions from review sessions, grouped by feature area.',
			status: 'recent',
			accent: 'amber',
			locationPath: ['LFM', 'Shared', 'Feedback Clips'],
			tags: ['feedback', 'video'],
			collaborators: ['Research'],
			pinned: false
		}
	],
	trash: [
		{
			id: 'trash-legacy-icons',
			name: 'Legacy Icons.sketch',
			kind: 'file',
			category: 'image',
			typeLabel: 'Archived design file',
			sizeLabel: '12 MB',
			sortSize: 12000,
			modifiedAt: '2026-04-18T08:18:00.000Z',
			preview: 'Discarded icon exploration replaced by the current flatter glyph system.',
			status: 'local',
			accent: 'slate',
			locationPath: ['LFM', 'Trash', 'Legacy Icons.sketch'],
			tags: ['deprecated'],
			collaborators: ['Design'],
			pinned: false
		},
		{
			id: 'trash-archive-2025',
			name: 'Archive 2025.zip',
			kind: 'file',
			category: 'archive',
			typeLabel: 'Compressed archive',
			sizeLabel: '1.1 GB',
			sortSize: 1100000,
			modifiedAt: '2026-04-14T16:40:00.000Z',
			preview: 'Obsolete 2025 exports and duplicate onboarding assets awaiting purge.',
			status: 'local',
			accent: 'slate',
			locationPath: ['LFM', 'Trash', 'Archive 2025.zip'],
			tags: ['cleanup'],
			collaborators: ['You'],
			pinned: false
		},
		{
			id: 'trash-old-trailer',
			name: 'Old Trailer Cut.mp4',
			kind: 'file',
			category: 'video',
			typeLabel: 'Superseded video',
			sizeLabel: '248 MB',
			sortSize: 248000,
			modifiedAt: '2026-04-12T11:06:00.000Z',
			preview: 'First cut removed after script and timing changes for the final launch reel.',
			status: 'local',
			accent: 'slate',
			locationPath: ['LFM', 'Trash', 'Old Trailer Cut.mp4'],
			tags: ['obsolete'],
			collaborators: ['Creative'],
			pinned: false
		},
		{
			id: 'trash-unused-mockups',
			name: 'Unused Mockups',
			kind: 'folder',
			category: 'folder',
			typeLabel: 'Discarded folder',
			sizeLabel: '14 items',
			sortSize: 14,
			modifiedAt: '2026-04-10T09:14:00.000Z',
			preview: 'Older product renderings no longer aligned with the current shell direction.',
			status: 'local',
			accent: 'slate',
			locationPath: ['LFM', 'Trash', 'Unused Mockups'],
			tags: ['cleanup'],
			collaborators: ['Design'],
			pinned: false
		}
	]
};

export const activityLibrary: Record<string, ActivityEntry[]> = {
	'home-design-sprint': [
		{ id: 'a1', title: 'New preview set uploaded', summary: 'Updated hero states were added for tomorrow’s review.', timeLabel: '9 min ago', tone: 'success' },
		{ id: 'a2', title: 'Pinned to quick access', summary: 'Kept visible in Home for the current sprint window.', timeLabel: 'Today', tone: 'info' },
		{ id: 'a3', title: 'Shared with product', summary: 'A read-only link was generated for leadership comments.', timeLabel: 'Yesterday', tone: 'attention' }
	],
	'proj-lfm-shell': [
		{ id: 'b1', title: 'UI shell refreshed', summary: 'Explorer chrome was updated with the new glass surface system.', timeLabel: '4 min ago', tone: 'success' },
		{ id: 'b2', title: 'Routing synced', summary: 'Section-aware routes now keep sidebar and tabs aligned.', timeLabel: 'Today', tone: 'info' },
		{ id: 'b3', title: 'Preview rail refined', summary: 'Metadata blocks were reordered for faster scanning.', timeLabel: 'Yesterday', tone: 'attention' }
	],
	'shared-design-review': [
		{ id: 'c1', title: 'Comments condensed', summary: 'Feedback tags were grouped by navigation, density, and motion.', timeLabel: '12 min ago', tone: 'success' },
		{ id: 'c2', title: 'Three clips restored', summary: 'Stakeholder recordings were moved back from the archive.', timeLabel: 'Today', tone: 'info' },
		{ id: 'c3', title: 'Pending decision', summary: 'Toolbar wording still needs sign-off from product marketing.', timeLabel: 'Yesterday', tone: 'attention' }
	]
};
